export const objlist = [
    {
    data:{
        id:4563,
        name:"mountain",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnYIR39Em1n_TNeYstxHF6NHVxqwvlf3wNLg&s"
    }
},
{
    data:{
        id:4378,
        name:"lake",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnYIR39Em1n_TNeYstxHF6NHVxqwvlf3wNLg&s"
         }
},
{
    data:{
        id:2312,
        name:"horse",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnYIR39Em1n_TNeYstxHF6NHVxqwvlf3wNLg&s"
         }
},
{
    data:{
        id:5677,
        name:"apple",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnYIR39Em1n_TNeYstxHF6NHVxqwvlf3wNLg&s"
         }
},
{
    data:{
        id:4234,
        name:"fish",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnYIR39Em1n_TNeYstxHF6NHVxqwvlf3wNLg&s"
         }
},
{
    data:{
        id:4980,
        name:"panda",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeC96FEKIa_ht6uKdEZyNLgsGJ7iT8zfMvNg&s"
         }
}
]